name: Shell script
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  greet:
    name: Ubuntu OS setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/../actions.sh"

          "${GITHUB_WORKSPACE}/../actions.sh"
